name: Debug CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Dev and Debug Workflows

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - "5.2.0"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-repositories: |
            pin: git+https://github.com/ocaml/opam-repository#dbc9ec7b83bac3673185542221a571372b6abb35
          opam-disable-sandboxing: true

      - name: Install system dependencies (Linux)
        run: sudo apt update && sudo apt-get install libev-dev libonig-dev libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - name: Install system dependencies (macOS)
        run: brew update && brew reinstall libev openssl@3 # Openssl is a workaround for https://github.com/ocaml/opam-repository/issues/19676
        if: runner.os == 'macOS'

      - name: Install opam dependencies
        run: opam install --deps-only --with-test .

      - name: Install ocamlformat
        run: opam install ocamlformat.0.26.2

      - name: Build project
        run: opam exec -- dune build @install

      - name: Run tests
        run: opam exec -- make test

      - name: Format code
        run: opam exec -- dune build --auto-promote @fmt
        if: runner.os == 'Linux'
